class PostFail3 {
    var a:Int := 5

    method test1(a:Int) {
        if true
            self.a := a
    }
    @post(self.a = a)
    
    method test2(a:Int) {
        self.a += 1
    }
    @post(self.a = @pre(self.a) + 1)
    
    @class
    @pre(v >= 0)
    method test3(v:Int):Int {
        return v * v
    }
    @post(@return < v)
    
    @class
    method main() {
        var p := PostFail3()
        p.test1(10)
        p.test2(10)
        Console.writeLine(p.a)
        try {
            Console.writeLine(test3(64))
        }
        catch e:AssertionError {
            Console.writeLine("success")
        }
    }
}